services:
  backend:
    build:
      context: backend
      dockerfile: ./backend.Dockerfile
    image: worldhopper-backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      WorldHopper__DataPath: /data
    volumes:
      - ${WORLDHOPPER_DATA_PATH:-./.worldhopper-data}:/data:ro
  frontend:
    build:
      context: frontend
      dockerfile: ./frontend.Dockerfile
    image: worldhopper-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend