/*

			PROGRAM TO :	1).INPUT THE VALUE OF TEMPERATURE IN FAHRENHEIT (degrees)
					2).COMPUTE AND PRINT THE CORRESPONDING VALUE OF TEMPERATURE IN CELCIUS (degrees)

*/

#include<stdio.h>			//  IMPORTS THE STANDARD INPUT/OTPUT HEADER FILE INTO THE PROGRAM
int main()
{
 double F,C;				//  DECLARES TWO VARIABLES "F" (FOR FAHRENHEIT) AND "C" (FOR CELCIUS) WHICH CAN HOLD FLOATING POINT VALUES
 printf("\n\tEnter the value(floating point) of temperature in Fahrenheit scale : ");	//  \n = NEW LINE CHARACTER AND \t = TAB CHARACTER
 scanf("%lf",&F);			//  %x SPECIFIES  scanf OF THE DATATYPE TO READ WHILE &X CREATES A MEMORY ADDRESS FOR VARIABLE "X"
 C = (5.0 / 9.0) * (F - 32.0);		//  SIMPLY WRITING 5/9 WOULD  RESULT IN C BEING ZERO BECAUSE 5/9 WOULD BE INTERPRETED TO BE A DIVISION OF INTEGER TYPE NUMBERS
 printf("\n\tValue of temperature in Celcius scale is : %lf degrees\n\n",C);		//  %x SPECIFIES PRINTF OF THE DATATYPE TO OUTPUT AND OF ITS PRINT-LOCATION
}
